version: "3.9"
services:
  db:
    image: kartoza/postgis
    privileged: true
    restart: always
    ports:
      - 54327:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: long_memory_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql:/var/lib/postgresql
